### ISSUE TITLE
GameOVER!

### ISSUE THREAD

**Issue by pixxon** [pixxon/Labyrinth#10]
Lets have end of game when the player reaches the destination.
Also highlight the end with something nice.

**Comment by mykeesg** [comment]
fieldtype added in the enumerator, still needing to make make a textured object for it.

**Comment by pixxon** [comment]
Textured object is done, but the model doesn't support end of game.

**Comment by mykeesg** [comment]
some kind of event still required to be fired, as the game just restarts now when reaching the exit.

**Comment by pixxon** [comment]
That will do for now. In v2.0 we will go deeper into this.
